version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: planty-postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: planty
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5434"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d planty"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: planty-mcp
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5434
      DB_USER: username
      DB_PASSWORD: password
      DB_NAME: planty
      PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data:
